### ISSUE TITLE
Teensy3.1 and R61059

### ISSUE THREAD

**Issue by jox1a** [prenticedavid/MCUFRIEND_kbv#140]
Hi. David
I use your library in standard configuration with Teensy3.1 and R61059 it works well.
LCD 3inch 240x400 R61059V ----- Teensy
RST-A4
CS --A3
RS --A2
WR--A1
RD--A0
DO--8
D1--9
D2--2
D3--3
D4--4
D5--5
D6--6
D7--7
I don't use any kind of shield
I working on a power supply project  I  have my custom PCB 
but I made a mistake before and I didn't check a pinout in your library.
so now I have PCB  But I don't know exactly how to change pins set for 

RST-A8
CS --A2
RS --A3
WR--A6
RD--A7
DO--24
D1--25
D2--26
D3--27
D4--28
D5--29
D6--30
D7--31
is it even possible?

**Comment by prenticedavid** [comment]
@jox1a,

A fellow reader has the same Open-Smart 3.3V board.

Since you have a Teensy3.2 which is much faster than a Due,   please can you verify that the R61509V can run reliably at high speed.

e.g. overclock the Teensy from the Arduino IDE.   Do you get glitches in graphictest_kbv.ino ?
Please report.

David.
