### ISSUE TITLE
Work in progress Fast show BMP

### ISSUE THREAD

**Issue by gabiiel** [prenticedavid/MCUFRIEND_kbv#192]
I have made a file reader that reads a 16bit image and displays it to the screen in 1.5 seconds, it can also read a 1bit image and display it in 650ms using an arduino UNO
For now it only works with full 320x480 images but that can be improved later
All it uses is a new SdFat library, it's mostly backward compatible with standard SD library(for this example it's fully), but it's much slower
I will add support for different resolutions, different drawing areas, to read 24 bit images
Any comments is much appreciated
[SuperFast_1___16bit_bmp_uno.zip](https://github.com/prenticedavid/MCUFRIEND_kbv/files/7567584/SuperFast_1___16bit_bmp_uno.zip)

**Comment by prenticedavid** [comment]
I provide an example sketch that displays different format .BMP files from SD Card.

Yes,  you can optimise for 1-bit.  And for 16-bit.
You will probably gain speed with SdFat.h instead of SD.h

There is little point in ignoring the W x H dimensions.

You can use a regular C++ function like my example.
Or you can create a C++ class.

Whichever floats your boat.

David.
