### ISSUE TITLE
Support for MKR1000

### ISSUE THREAD

**Issue by LRagji** [prenticedavid/MCUFRIEND_kbv#3]
It says support for Zero on its readme, but cant find its connection diagram or pin mapping for the same My case is i need to make this work with MKR1000

**Comment by prenticedavid** [comment]
I do not have a MKR1000.
It should be simple enough to add the pin mapping.

The Zero is simple.   You can only mate a Shield with the Zero in one way.
Hence I know the pin mapping.

If you tell me your connections,  I can add a SPECIAL.    Since the MKR1000 does not have proper Uno headers,   I will not add it to mcufriend_shield.h  (unless there is an official shield Adapter)

David.
