### ISSUE TITLE
ID 9403

### ISSUE THREAD

**Issue by iotexpert** [prenticedavid/MCUFRIEND_kbv#70]
David... Thank for you for the library... it has been super helpful.

I can see that you identify x9403 ...  My question is, what Driver Chip is it?

Do you have the Datasheet?

I dont see any of the data sheets in your repository, do you put them someplace else?

I notice that I have a ILI9341 that doesnt completely comply with the Datasheet... the more I read the more I’m convinced there are “counterfeit” chips out there.

Anyway... thanks again for your work.

Thanks,
Alan
engineer@iotexpert.com

**Comment by prenticedavid** [comment]
The readID() method checks for some "odd case" ID locations.    Otherwise it simply returns values found in 0xD3 or 0x00.

Ilitek devices return 0x91xx, 0x932x, 0x933x, 0x948x, 0x980x, ... 
Sitronix return 0x773x, 0x778x, 0x779x, ...
Other manufacturers sometimes mimic the Ilitek ID locations.   e.g. several will return 0x9325.   RM68140 returns 0x9486 from 0xD3

No,   I have never posted the datasheets.   No,   I do not have datasheets for every controller that I "support".

I have no idea where 0x9403 comes from.    If you want help,  run the LCD_ID_readreg sketch and paste the report.    Preferably to the public Arduino/Displays Forum

I have datasheets for ILI9341, ILI9341V.   The default Gamma registers are different.
Paste the report for your "unknown" device.

David.

**Comment by iotexpert** [comment]
Thanks.
