### ISSUE TITLE
ESP32 Uno Style

### ISSUE THREAD

**Issue by kuzmanzs** [prenticedavid/MCUFRIEND_kbv#98]
Hi,

I have ESP32 Uno Style board with 3.5" 8bit TFT.
Display is working but touchsreen doens nonse sensing any touch. I want run your https://github.com/prenticedavid/MCUFRIEND_kbv/tree/master/examples/TouchScreen_Calibr_native
but I have recognized in setup following is:
#if defined(__arm__) || defined(ESP32)
    Serial.println(F("Not possible to diagnose Touch pins on ARM or ESP32"));

above looks like it is working with ESP32:
#if defined(ESP32)
int XP = 27, YP = 4, XM = 15, YM = 14;  //most common configuration

This constellation is contradictory. Could you tell me it will work ESP?
I have done following 4 pin modification on esp32 board:
https://github.com/s60sc/Adafruit_TouchScreen

**Comment by prenticedavid** [comment]
Yes,   you can use a Resistive Touchscreen with ARM or ESP32.

However I can only diagnose the X, Y pins on AVR.
Which is why you have to measure the Touchscreen resistance with a DMM.

If you don't have a DMM,   plug the shield into a Uno and do the Calibration with the Uno.
Paste the Calibration report directly from the Serial Terminal.  e.g.
```

const int XP=7,XM=A1,YP=A2,YM=6; //ID=0x7783
const int TS_LEFT=208,TS_RT=877,TS_TOP=102,TS_BOT=897;

```

David.
